<a href="https://colab.research.google.com/github/PasiAbey/Anomaly_Detection/blob/main/Anomaly_Detection_Gradiant_Distribution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


from sklearn.model_selection import train_test_split


In [ ]:
file_path = '/content/drive/MyDrive/Data_sets/creditcard.csv'

In [ ]:
df = pd.read_csv(file_path)

In [ ]:
df.head(5)

Time        V1        V2        V3        V4        V5        V6        V7  \
0     0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1     0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2     1 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3     1 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4     2 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62    0.0  
1  0.125895 -0.008983  0.014724    2.69    0.0  
2 -0.139097 -0.055353 -0.059752  378.66    0.0  
3 -0.221929  0.062723  0.061458  123.50    0.0  
4  0.502292  0.219422  0.215153   69.99    0.0  

[5 rows x 31 columns]

In [ ]:
df.describe()

Time            V1            V2            V3            V4  \
count  63472.000000  63472.000000  63472.000000  63472.000000  63472.000000   
mean   32876.370951     -0.239755     -0.012681      0.685110      0.171481   
std    13937.620130      1.859165      1.655059      1.431606      1.380519   
min        0.000000    -56.407510    -72.715728    -32.965346     -5.172595   
25%    27310.750000     -0.998583     -0.585916      0.200353     -0.723986   
50%    36494.500000     -0.243451      0.074815      0.775927      0.187217   
75%    43273.250000      1.154107      0.730518      1.409732      1.053796   
max    50731.000000      1.960497     18.183626      4.101716     16.715537   

                 V5            V6            V7            V8            V9  \
count  63472.000000  63472.000000  63472.000000  63472.000000  63472.000000   
mean      -0.265122      0.102611     -0.113445      0.060235      0.046152   
std        1.390607      1.305557      1.248892      1.186829      1.173754   
min      -42.147898    -26.160506    -26.548144    -41.484823     -9.283925   
25%       -0.884022     -0.636320     -0.604362     -0.143175     -0.657457   
50%       -0.297487     -0.150156     -0.073530      0.064232     -0.052724   
75%        0.274765      0.492800      0.423183      0.340827      0.707367   
max       34.801666     22.529298     36.677268     20.007208     10.392889   

       ...           V21           V22           V23           V24  \
count  ...  63471.000000  63471.000000  63471.000000  63471.000000   
mean   ...     -0.028187     -0.107593     -0.038773      0.006023   
std    ...      0.717475      0.636349      0.596221      0.596136   
min    ...    -20.262054    -10.933144    -26.751119     -2.836627   
25%    ...     -0.227571     -0.527888     -0.179561     -0.325172   
50%    ...     -0.062403     -0.082507     -0.051844      0.061251   
75%    ...      0.113836      0.307598      0.078972      0.402531   
max    ...     22.614889      5.805795     17.297845      4.014444   

                V25           V26           V27           V28        Amount  \
count  63471.000000  63471.000000  63471.000000  63471.000000  63471.000000   
mean       0.136433      0.020155      0.001909      0.004163     96.080659   
std        0.438851      0.498258      0.383913      0.322974    270.787460   
min       -7.495741     -2.534330     -8.567638     -9.617915      0.000000   
25%       -0.127732     -0.329552     -0.063137     -0.005981      7.680000   
50%        0.174146     -0.076052      0.009199      0.022698     26.220000   
75%        0.422721      0.296894      0.082428      0.076330     88.000000   
max        5.525093      3.517346     11.135740     33.847808  19656.530000   

             Class  
count  63471.00000  
mean       0.00260  
std        0.05092  
min        0.00000  
25%        0.00000  
50%        0.00000  
75%        0.00000  
max        1.00000  

[8 rows x 31 columns]

In [ ]:
#Remove the Rows which does not include value in Class Column

df_cleaned = df.dropna(subset=['Class'])

In [ ]:
df_cleaned.describe()

Time            V1            V2            V3            V4  \
count  63471.000000  63471.000000  63471.000000  63471.000000  63471.000000   
mean   32876.089647     -0.239754     -0.012665      0.685084      0.171504   
std    13937.549740      1.859180      1.655067      1.431602      1.380517   
min        0.000000    -56.407510    -72.715728    -32.965346     -5.172595   
25%    27310.500000     -0.998598     -0.585863      0.200348     -0.723960   
50%    36494.000000     -0.243442      0.074820      0.775911      0.187223   
75%    43273.000000      1.154109      0.730532      1.409712      1.053800   
max    50731.000000      1.960497     18.183626      4.101716     16.715537   

                 V5            V6            V7            V8            V9  \
count  63471.000000  63471.000000  63471.000000  63471.000000  63471.000000   
mean      -0.265098      0.102609     -0.113427      0.060231      0.046180   
std        1.390604      1.305567      1.248894      1.186838      1.173742   
min      -42.147898    -26.160506    -26.548144    -41.484823     -9.283925   
25%       -0.883987     -0.636334     -0.604336     -0.143176     -0.657425   
50%       -0.297446     -0.150158     -0.073504      0.064229     -0.052724   
75%        0.274771      0.492800      0.423185      0.340830      0.707376   
max       34.801666     22.529298     36.677268     20.007208     10.392889   

       ...           V21           V22           V23           V24  \
count  ...  63471.000000  63471.000000  63471.000000  63471.000000   
mean   ...     -0.028187     -0.107593     -0.038773      0.006023   
std    ...      0.717475      0.636349      0.596221      0.596136   
min    ...    -20.262054    -10.933144    -26.751119     -2.836627   
25%    ...     -0.227571     -0.527888     -0.179561     -0.325172   
50%    ...     -0.062403     -0.082507     -0.051844      0.061251   
75%    ...      0.113836      0.307598      0.078972      0.402531   
max    ...     22.614889      5.805795     17.297845      4.014444   

                V25           V26           V27           V28        Amount  \
count  63471.000000  63471.000000  63471.000000  63471.000000  63471.000000   
mean       0.136433      0.020155      0.001909      0.004163     96.080659   
std        0.438851      0.498258      0.383913      0.322974    270.787460   
min       -7.495741     -2.534330     -8.567638     -9.617915      0.000000   
25%       -0.127732     -0.329552     -0.063137     -0.005981      7.680000   
50%        0.174146     -0.076052      0.009199      0.022698     26.220000   
75%        0.422721      0.296894      0.082428      0.076330     88.000000   
max        5.525093      3.517346     11.135740     33.847808  19656.530000   

             Class  
count  63471.00000  
mean       0.00260  
std        0.05092  
min        0.00000  
25%        0.00000  
50%        0.00000  
75%        0.00000  
max        1.00000  

[8 rows x 31 columns]

In [ ]:
df = df_cleaned

In [ ]:
fraud_count = sum(df.Class == 1)


fraud_count

165

In [ ]:
normal_count = sum(df.Class == 0)

normal_count

63306

In [ ]:
fraud_count + normal_count

63471

In [ ]:
X = df.drop(['Class', 'Time'], axis = 1)

In [ ]:
y = df.Class

In [ ]:
#Split the Data set into train, cross validation and test


X_temp, X_test, y_temp, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)


X_train, X_cv, y_train, y_cv = train_test_split(X_temp, y_temp, test_size=0.25, random_state=42, stratify=y_temp)

In [ ]:
X_test.shape

(12695, 29)

In [ ]:
y_test.shape

(12695,)

In [ ]:
X_cv.shape

(12694, 29)

In [ ]:
X_train.shape

(38082, 29)

In [ ]:
is_normal = (y_train == 0) #Make new X_train, which only inlude normal ones

In [ ]:
X_train_normal = X_train[is_normal]

In [ ]:
X_train.shape

(38082, 29)

In [ ]:
X_train_normal.shape

(37983, 29)

In [ ]:
#For Testing Purpose

#X_train_normal = np.array(X_train_normal)

In [ ]:
#Plot some histograms

In [ ]:
"""  fig, axes = plt.subplots(6, 5, figsize=(20, 4 * 6))
axes = axes.flatten() # Flatten the 2D array of axes for easier iteration


for i, col in enumerate(X_train_normal.columns):
    # Plot histogram
    axes[i].hist(X_train_normal[col], bins=500, color='blue', alpha=0.7)
    axes[i].set_title(col) """

"  fig, axes = plt.subplots(6, 5, figsize=(20, 4 * 6))\naxes = axes.flatten() # Flatten the 2D array of axes for easier iteration\n\n\nfor i, col in enumerate(X_train_normal.columns):\n    # Plot histogram\n    axes[i].hist(X_train_normal[col], bins=500, color='blue', alpha=0.7)\n    axes[i].set_title(col) "

In [ ]:
#Convert DataDrames into Array

X_train_normal = np.array(X_train_normal)
X_val = np.array(X_cv)
X_test = np.array(X_test)

In [ ]:
X_train_normal.shape

(37983, 29)

###Estimate Guassian

In [ ]:
def est_guassian(X):
  m, n = X.shape

  mu = np.mean(X, axis=0)
  var = np.mean((X - mu)**2, axis = 0)

  return mu, var

mu, var = est_guassian(X_train_normal)
print(f"Estimate Mean of each feature: \n{mu}\n")
print(f"Estimate Variance of each feature: \n{var}\n")

Estimate Mean of each feature: 
[-2.30002858e-01 -2.61647616e-02  7.10276614e-01  1.63717319e-01
 -2.47710149e-01  1.10775119e-01 -9.30786288e-02  4.84275187e-02
  5.54556589e-02 -1.87770464e-02  3.06932342e-01 -1.94653715e-01
  9.64587028e-02  1.39616990e-01  1.41029243e-01  3.17746252e-03
  1.20404207e-01 -8.16255986e-02 -2.55848282e-02  4.48030740e-02
 -2.68416471e-02 -1.09977752e-01 -3.75325546e-02  5.49824365e-03
  1.37592711e-01  1.82922501e-02  1.82593436e-03  4.00489620e-03
  9.63531569e+01]

Estimate Variance of each feature: 
[3.20338049e+00 2.71246231e+00 1.51934670e+00 1.82848004e+00
 1.71478899e+00 1.68997508e+00 1.21503069e+00 1.29033461e+00
 1.33448898e+00 1.02009214e+00 1.12143482e+00 1.33600777e+00
 1.18256501e+00 8.70971750e-01 8.80763548e-01 7.36706218e-01
 6.66302594e-01 6.90654457e-01 6.63544671e-01 5.72621138e-01
 5.39268561e-01 4.09125721e-01 3.63903173e-01 3.57323111e-01
 1.91754077e-01 2.47334730e-01 1.41057108e-01 1.14098131e-01
 7.37234883e+04]



### Test

In [ ]:
#For Testing Purpose

var.shape


var.ndim


X_train_normal



test = np.array(X_train_normal)

print(type(test))



test.shape

<class 'numpy.ndarray'>


(37983, 29)

In [ ]:
from utils import *

###Compute the Probability Density

In [ ]:
p_train = multivariate_gaussian(X_train_normal, mu, var)


In [ ]:
p_train

array([8.21841916e-15, 6.04994664e-20, 1.21124871e-16, ...,
       3.27674145e-17, 1.81826560e-18, 1.15788530e-18])

###Compute the Probability Desity for Cross Validation set

In [ ]:
p_val = multivariate_gaussian(X_val, mu, var)


p_val.shape

(12694,)

In [ ]:
p_val

array([4.28148092e-17, 3.36883648e-15, 5.01855236e-17, ...,
       1.25682835e-19, 3.80933576e-23, 4.45343721e-16])

In [ ]:
#For Testing Perpose"

print(f"Max probability in Validation set: {max(p_val)}")
print(f"Minimum probability in Validation set: {min(p_val)}\n\n")

Max probability in Validation set: 3.9230351136617734e-14
Minimum probability in Validation set: 0.0




In [ ]:
###For Test

p_val.shape

(12694,)

In [ ]:
## cv and val is same by names

###Find the Threshold

In [ ]:
def select_threshold(y_val, p_val):

    best_epsilon = 0
    best_F1 = 0
    F1 = 0

    step_size = (max(p_val) - min(p_val)) / 1000

    for epsilon in np.arange(min(p_val), max(p_val), step_size):


        predictions = (epsilon > p_val)


        tp = (sum((predictions == 1) & (y_val == 1)))
        fp = (sum((predictions == 1) & (y_val == 0)))
        fn = (sum((predictions == 0) & (y_val == 1)))


        ### Check for Zero Division
        if (tp + fp) == 0:
            prec = 0
        else:
            prec = tp / (tp + fp)



        if (tp + fn) == 0:
            rec = 0
        else:
            rec = tp / (tp + fn)




        if (prec + rec) == 0:
            F1 = 0
        else:
            F1 = (2 * prec * rec) / (prec + rec)




        if F1 > best_F1:
            best_F1 = F1
            best_epsilon = epsilon

    return best_epsilon, best_F1, predictions




epsilon, f1, pred = select_threshold(y_cv, p_val)

In [ ]:
print(f"Epsilon is: {epsilon}\n\n")

print(f"F1 score is: {f1}")


pred

Epsilon is: 3.9230351136617734e-17


F1 score is: 0.010604805302402652


array([ True,  True,  True, ...,  True,  True,  True])

##Now Check this on Test Dataset

In [ ]:
y_test = np.array(y_test)

In [ ]:
test_mean, test_var = est_guassian(X_test) #Get mean and Variance for Test Data

In [ ]:
p_test = multivariate_gaussian(X_test, test_mean, test_var) #Find the Probability Distribution for Test Data

In [ ]:
test_predict = (p_test < epsilon)

In [ ]:
tp = (sum((test_predict == 1) & (y_test == 1)))
fp = (sum((test_predict == 1) & (y_test == 0)))
fn = (sum((test_predict == 0) & (y_test == 1)))

## Final Evaluation

In [ ]:
print(f"Actual Positives in Test set: {sum(y_test == 1)}")

print(f"Predicted Positives in Test Set: {tp}")

Actual Positives in Test set: 33
Predicted Positives in Test Set: 32
